config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ベジマルへようこそ"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'ベジマル'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Your Name All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
 <div class="container">
   <%
=begin%>
 <%= link_to(image_tag("header_logo.jpeg", :alt => ""), root_url, id: 'logo') %> 
<%
=end%>
   <nav>
     <ul class="nav navbar-nav navbar-right">
       <li><%= link_to 'ベジマルとは？', about_path %></li>
       <li><%= link_to 'ユーザー登録', signup_path %></li>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render  "layouts/rails_default" %>
    <%= render  "layouts/shim" %>
  </head>

  <body>
    <div id="page">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render  "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "ベジマルとは？") %>
<h1>ベジマルとは？</h1>

app/views/static_pages/home.html.erb
<center>
  <h1>ベジマルへようこそ！</h1>
</center>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<h1>利用規約</h1>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = 'form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation' %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "マイページ") %>
<h1>マイページ</h1>
<%= gravatar_for @user %><br>
<%= @user.id %>, <%= @user.name %>, <%= @user.email %>　<br>
<%= @user.created_at %>, <%= @user.updated_at %><br>